// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "GHCrawler": Models
//
// Command:
// $ goagen
// --design=github-crawler-api/design
// --out=$(GOPATH)\src\github-crawler-api
// --version=v1.2.0-dirty

package models

import (
	"context"
	"github.com/goadesign/goa"
	"github.com/jinzhu/gorm"
	"time"
)

// Location model
type Location struct {
	ID        int `gorm:"primary_key"` // primary key
	CreatedAt time.Time
	DeletedAt *time.Time
	Point     string `sql:"type:geometry(Point,4326)"`
	UpdatedAt time.Time
	UserID    int64
}

// TableName overrides the table name settings in Gorm to force a specific table name
// in the database.
func (m Location) TableName() string {
	return "locations"

}

// LocationDB is the implementation of the storage interface for
// Location.
type LocationDB struct {
	Db *gorm.DB
}

// NewLocationDB creates a new storage type.
func NewLocationDB(db *gorm.DB) *LocationDB {
	return &LocationDB{Db: db}
}

// DB returns the underlying database.
func (m *LocationDB) DB() interface{} {
	return m.Db
}

// LocationStorage represents the storage interface.
type LocationStorage interface {
	DB() interface{}
	List(ctx context.Context) ([]*Location, error)
	Get(ctx context.Context, id int) (*Location, error)
	Add(ctx context.Context, location *Location) error
	Update(ctx context.Context, location *Location) error
	Delete(ctx context.Context, id int) error
}

// TableName overrides the table name settings in Gorm to force a specific table name
// in the database.
func (m *LocationDB) TableName() string {
	return "locations"

}

// CRUD Functions

// Get returns a single Location as a Database Model
// This is more for use internally, and probably not what you want in  your controllers
func (m *LocationDB) Get(ctx context.Context, id int) (*Location, error) {
	defer goa.MeasureSince([]string{"goa", "db", "location", "get"}, time.Now())

	var native Location
	err := m.Db.Table(m.TableName()).Where("id = ?", id).Find(&native).Error
	if err == gorm.ErrRecordNotFound {
		return nil, err
	}

	return &native, err
}

// List returns an array of Location
func (m *LocationDB) List(ctx context.Context) ([]*Location, error) {
	defer goa.MeasureSince([]string{"goa", "db", "location", "list"}, time.Now())

	var objs []*Location
	err := m.Db.Table(m.TableName()).Find(&objs).Error
	if err != nil && err != gorm.ErrRecordNotFound {
		return nil, err
	}

	return objs, nil
}

// Add creates a new record.
func (m *LocationDB) Add(ctx context.Context, model *Location) error {
	defer goa.MeasureSince([]string{"goa", "db", "location", "add"}, time.Now())

	err := m.Db.Create(model).Error
	if err != nil {
		goa.LogError(ctx, "error adding Location", "error", err.Error())
		return err
	}

	return nil
}

// Update modifies a single record.
func (m *LocationDB) Update(ctx context.Context, model *Location) error {
	defer goa.MeasureSince([]string{"goa", "db", "location", "update"}, time.Now())

	obj, err := m.Get(ctx, model.ID)
	if err != nil {
		goa.LogError(ctx, "error updating Location", "error", err.Error())
		return err
	}
	err = m.Db.Model(obj).Updates(model).Error

	return err
}

// Delete removes a single record.
func (m *LocationDB) Delete(ctx context.Context, id int) error {
	defer goa.MeasureSince([]string{"goa", "db", "location", "delete"}, time.Now())

	var obj Location

	err := m.Db.Delete(&obj, id).Error

	if err != nil {
		goa.LogError(ctx, "error deleting Location", "error", err.Error())
		return err
	}

	return nil
}
