// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "GHCrawler": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github-crawler-api/design
// --out=$(GOPATH)\src\github-crawler-api
// --version=v1.2.0-dirty

package app

import (
	"fmt"
	"strings"
)

// CommitsHref returns the resource href.
func CommitsHref(commitID interface{}) string {
	paramcommitID := strings.TrimLeftFunc(fmt.Sprintf("%v", commitID), func(r rune) bool { return r == '/' })
	return fmt.Sprintf("/v1/commits/%v", paramcommitID)
}
