basePath: /v1
consumes:
- application/json
- application/x-www-form-urlencoded
definitions:
  Commit:
    description: Commit data (default view)
    example:
      authorOfCommit:
        id: 5.4301856e+18
        locationForUser:
          id: 1.1409709e+18
          lat: 0.5667709
          lng: 0.45074025
          location_string: Sit et esse maiores sit.
        login: Consequatur eos atque similique.
        type: Consectetur sunt asperiores dolor necessitatibus quasi suscipit.
      id: 8.348355e+18
      message: Soluta natus doloribus.
      sha: Sint cupiditate ratione.
      timestamp: 1978-06-20T04:46:16+02:00
    properties:
      authorOfCommit:
        $ref: '#/definitions/Ghuser'
      id:
        description: ID of the commit in the database
        example: 8.348355e+18
        format: int64
        type: integer
      message:
        description: Message of the commit
        example: Soluta natus doloribus.
        type: string
      sha:
        description: Unique identifier of the commit
        example: Sint cupiditate ratione.
        type: string
      timestamp:
        description: Time the commit happened
        example: 1978-06-20T04:46:16+02:00
        format: date-time
        type: string
    required:
    - id
    - sha
    - authorOfCommit
    - timestamp
    title: 'Mediatype identifier: application/vnd.commit+json; view=default'
    type: object
  CommitCollection:
    description: CommitCollection is the media type for an array of Commit (default
      view)
    example:
    - authorOfCommit:
        id: 5.4301856e+18
        locationForUser:
          id: 1.1409709e+18
          lat: 0.5667709
          lng: 0.45074025
          location_string: Sit et esse maiores sit.
        login: Consequatur eos atque similique.
        type: Consectetur sunt asperiores dolor necessitatibus quasi suscipit.
      id: 8.348355e+18
      message: Soluta natus doloribus.
      sha: Sint cupiditate ratione.
      timestamp: 1978-06-20T04:46:16+02:00
    items:
      $ref: '#/definitions/Commit'
    title: 'Mediatype identifier: application/vnd.commit+json; type=collection; view=default'
    type: array
  Ghuser:
    description: GH user data (default view)
    example:
      id: 5.4301856e+18
      locationForUser:
        id: 1.1409709e+18
        lat: 0.5667709
        lng: 0.45074025
        location_string: Sit et esse maiores sit.
      login: Consequatur eos atque similique.
      type: Consectetur sunt asperiores dolor necessitatibus quasi suscipit.
    properties:
      id:
        description: ID of the user in the database
        example: 5.4301856e+18
        format: int64
        type: integer
      locationForUser:
        $ref: '#/definitions/Location'
      login:
        description: Unique username of the user
        example: Consequatur eos atque similique.
        type: string
      type:
        description: Type of the user
        example: Consectetur sunt asperiores dolor necessitatibus quasi suscipit.
        type: string
    required:
    - id
    - login
    - type
    title: 'Mediatype identifier: application/vnd.ghuser+json; view=default'
    type: object
  GhuserCollection:
    description: GhuserCollection is the media type for an array of Ghuser (default
      view)
    example:
    - id: 5.4301856e+18
      locationForUser:
        id: 1.1409709e+18
        lat: 0.5667709
        lng: 0.45074025
        location_string: Sit et esse maiores sit.
      login: Consequatur eos atque similique.
      type: Consectetur sunt asperiores dolor necessitatibus quasi suscipit.
    items:
      $ref: '#/definitions/Ghuser'
    title: 'Mediatype identifier: application/vnd.ghuser+json; type=collection; view=default'
    type: array
  Location:
    description: Location as geocoordinates (default view)
    example:
      id: 1.1409709e+18
      lat: 0.5667709
      lng: 0.45074025
      location_string: Sit et esse maiores sit.
    properties:
      id:
        description: ID of the location in the database
        example: 1.1409709e+18
        format: int64
        type: integer
      lat:
        description: coordinates lat
        example: 0.5667709
        format: double
        type: number
      lng:
        description: coordinates lng
        example: 0.45074025
        format: double
        type: number
      location_string:
        description: Location as specified by user
        example: Sit et esse maiores sit.
        type: string
    required:
    - id
    - lat
    - lng
    title: 'Mediatype identifier: application/vnd.location+json; view=default'
    type: object
  Repository:
    description: Commit data (default view)
    example:
      first_commit:
        authorOfCommit:
          id: 5.4301856e+18
          locationForUser:
            id: 1.1409709e+18
            lat: 0.5667709
            lng: 0.45074025
            location_string: Sit et esse maiores sit.
          login: Consequatur eos atque similique.
          type: Consectetur sunt asperiores dolor necessitatibus quasi suscipit.
        id: 8.348355e+18
        message: Soluta natus doloribus.
        sha: Sint cupiditate ratione.
        timestamp: 1978-06-20T04:46:16+02:00
      full_name: Possimus distinctio quas harum quaerat enim.
      id: 1.9539887e+18
      org: true
      owner: Harum quibusdam omnis non quis repudiandae.
      project_id: 0.8593949
    properties:
      first_commit:
        $ref: '#/definitions/Commit'
      full_name:
        description: Full name of the repo
        example: Possimus distinctio quas harum quaerat enim.
        type: string
      id:
        description: ID of the commit in the database
        example: 1.9539887e+18
        format: int64
        type: integer
      org:
        description: If owner is an organization
        example: true
        type: boolean
      owner:
        description: Name of the owner of the repository
        example: Harum quibusdam omnis non quis repudiandae.
        type: string
      project_id:
        description: Time the commit happened
        example: 0.8593949
        format: double
        type: number
    required:
    - id
    - owner
    - full_name
    - project_id
    title: 'Mediatype identifier: application/vnd.repository+json; view=default'
    type: object
  RepositoryCollection:
    description: RepositoryCollection is the media type for an array of Repository
      (default view)
    example:
    - first_commit:
        authorOfCommit:
          id: 5.4301856e+18
          locationForUser:
            id: 1.1409709e+18
            lat: 0.5667709
            lng: 0.45074025
            location_string: Sit et esse maiores sit.
          login: Consequatur eos atque similique.
          type: Consectetur sunt asperiores dolor necessitatibus quasi suscipit.
        id: 8.348355e+18
        message: Soluta natus doloribus.
        sha: Sint cupiditate ratione.
        timestamp: 1978-06-20T04:46:16+02:00
      full_name: Possimus distinctio quas harum quaerat enim.
      id: 1.9539887e+18
      org: true
      owner: Harum quibusdam omnis non quis repudiandae.
      project_id: 0.8593949
    items:
      $ref: '#/definitions/Repository'
    title: 'Mediatype identifier: application/vnd.repository+json; type=collection;
      view=default'
    type: array
  error:
    description: Error response media type (default view)
    example:
      code: invalid_value
      detail: Value of ID must be an integer
      id: 3F1FKVRR
      meta:
        timestamp: 1.458609e+09
      status: "400"
    properties:
      code:
        description: an application-specific error code, expressed as a string value.
        example: invalid_value
        type: string
      detail:
        description: a human-readable explanation specific to this occurrence of the
          problem.
        example: Value of ID must be an integer
        type: string
      id:
        description: a unique identifier for this particular occurrence of the problem.
        example: 3F1FKVRR
        type: string
      meta:
        additionalProperties: true
        description: a meta object containing non-standard meta-information about
          the error.
        example:
          timestamp: 1.458609e+09
        type: object
      status:
        description: the HTTP status code applicable to this problem, expressed as
          a string value.
        example: "400"
        type: string
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
host: 86.87.235.82:8081
info:
  contact:
    email: rpjproost@gmail.com
    name: Rick Proost, Wim Spaargaren, Vincent Robbemond
    url: http://127.0.0.1
  description: API for retrieving specific data from the github crawler
  title: Visualization API for github crawler
  version: ""
paths:
  /repositories/{repoID}:
    get:
      description: Retrieve repository from db
      operationId: repositories#show
      parameters:
      - description: Repository ID
        in: path
        minimum: 1
        name: repoID
        required: true
        type: integer
      produces:
      - application/vnd.goa.error
      - application/vnd.repository+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Repository'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error'
        "404":
          description: Not Found
      schemes:
      - http
      summary: show repositories
      tags:
      - repositories
  /repositories/{repoID}/commits/{sha}:
    get:
      description: Retrieve commit from db
      operationId: commits#show
      parameters:
      - description: Repository ID
        in: path
        minimum: 1
        name: repoID
        required: true
        type: integer
      - description: SHA of the commit
        in: path
        name: sha
        required: true
        type: string
      produces:
      - application/vnd.goa.error
      - application/vnd.commit+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Commit'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error'
        "404":
          description: Not Found
      schemes:
      - http
      summary: show commits
      tags:
      - commits
  /repositories/{repoID}/commits/list:
    get:
      description: Retrieve commits between timespan with users
      operationId: commits#list
      parameters:
      - description: From date
        in: query
        name: from
        required: false
        type: string
      - description: Limit the results
        in: query
        name: limit
        required: false
        type: integer
      - description: Repository ID
        in: path
        minimum: 1
        name: repoID
        required: true
        type: integer
      - description: Till ID
        in: query
        name: until
        required: false
        type: string
      produces:
      - application/vnd.commit+json; type=collection
      - application/vnd.goa.error
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/CommitCollection'
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error'
        "404":
          description: Not Found
      schemes:
      - http
      summary: list commits
      tags:
      - commits
  /repositories/{repoID}/developers/list:
    get:
      description: Retrieve developers between timespan with users
      operationId: developers#list
      parameters:
      - description: From date
        in: query
        name: from
        required: false
        type: string
      - description: Limit the results
        in: query
        name: limit
        required: false
        type: integer
      - description: Repository ID
        in: path
        minimum: 1
        name: repoID
        required: true
        type: integer
      - description: Till ID
        in: query
        name: until
        required: false
        type: string
      produces:
      - application/vnd.goa.error
      - application/vnd.ghuser+json; type=collection
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/GhuserCollection'
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error'
        "404":
          description: Not Found
      schemes:
      - http
      summary: list developers
      tags:
      - developers
  /repositories/list:
    get:
      description: Retrieve all repositories in DB
      operationId: repositories#list
      produces:
      - application/vnd.goa.error
      - application/vnd.repository+json; type=collection
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/RepositoryCollection'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error'
      schemes:
      - http
      summary: list repositories
      tags:
      - repositories
produces:
- application/json
- application/xml
- application/gob
- application/x-gob
responses:
  NoContent:
    description: No Content
  NotFound:
    description: Not Found
  OK:
    description: OK
    schema:
      $ref: '#/definitions/Commit'
schemes:
- http
swagger: "2.0"
