// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "GHCrawler": commits Resource Client
//
// Command:
// $ goagen
// --design=github-crawler-api/design
// --out=$(GOPATH)\src\github-crawler-api
// --version=v1.2.0-dirty

package client

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strconv"
	"time"
)

// ListCommitsPath computes a request path to the list action of commits.
func ListCommitsPath(repoID int) string {
	param0 := strconv.Itoa(repoID)

	return fmt.Sprintf("/v1/repositories/%s/commits/list", param0)
}

// Retrieve commits between timespan with users
func (c *Client) ListCommits(ctx context.Context, path string, from *time.Time, limit *int, until *time.Time) (*http.Response, error) {
	req, err := c.NewListCommitsRequest(ctx, path, from, limit, until)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewListCommitsRequest create the request corresponding to the list action endpoint of the commits resource.
func (c *Client) NewListCommitsRequest(ctx context.Context, path string, from *time.Time, limit *int, until *time.Time) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	values := u.Query()
	if from != nil {
		tmp6 := from.Format(time.RFC3339)
		values.Set("from", tmp6)
	}
	if limit != nil {
		tmp7 := strconv.Itoa(*limit)
		values.Set("limit", tmp7)
	}
	if until != nil {
		tmp8 := until.Format(time.RFC3339)
		values.Set("until", tmp8)
	}
	u.RawQuery = values.Encode()
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}
