// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "GHCrawler": commits Resource Client
//
// Command:
// $ goagen
// --design=github-crawler-api/design
// --out=$(GOPATH)\src\github-crawler-api
// --version=v1.2.0-dirty

package client

import (
	"bytes"
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strconv"
)

// ListCommitsPath computes a request path to the list action of commits.
func ListCommitsPath() string {

	return fmt.Sprintf("/v1/commits/list")
}

// Retrieve commits between timespan with users
func (c *Client) ListCommits(ctx context.Context, path string, payload *ListPayload, contentType string) (*http.Response, error) {
	req, err := c.NewListCommitsRequest(ctx, path, payload, contentType)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewListCommitsRequest create the request corresponding to the list action endpoint of the commits resource.
func (c *Client) NewListCommitsRequest(ctx context.Context, path string, payload *ListPayload, contentType string) (*http.Request, error) {
	var body bytes.Buffer
	if contentType == "" {
		contentType = "*/*" // Use default encoder
	}
	err := c.Encoder.Encode(payload, &body, contentType)
	if err != nil {
		return nil, fmt.Errorf("failed to encode body: %s", err)
	}
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("POST", u.String(), &body)
	if err != nil {
		return nil, err
	}
	header := req.Header
	if contentType == "*/*" {
		header.Set("Content-Type", "application/json")
	} else {
		header.Set("Content-Type", contentType)
	}
	return req, nil
}

// ShowCommitsPath computes a request path to the show action of commits.
func ShowCommitsPath(commitID int) string {
	param0 := strconv.Itoa(commitID)

	return fmt.Sprintf("/v1/commits/%s", param0)
}

// Retrieve commit from db
func (c *Client) ShowCommits(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewShowCommitsRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewShowCommitsRequest create the request corresponding to the show action endpoint of the commits resource.
func (c *Client) NewShowCommitsRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}
