// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "GHCrawler": repositories Resource Client
//
// Command:
// $ goagen
// --design=github-crawler-api/design
// --out=$(GOPATH)\src\github-crawler-api
// --version=v1.2.0-dirty

package client

import (
	"bytes"
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strconv"
)

// ListRepositoriesPath computes a request path to the list action of repositories.
func ListRepositoriesPath() string {

	return fmt.Sprintf("/v1/repositories/list")
}

// Retrieve all repositories in DB
func (c *Client) ListRepositories(ctx context.Context, path string, payload *ListPayload, contentType string) (*http.Response, error) {
	req, err := c.NewListRepositoriesRequest(ctx, path, payload, contentType)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewListRepositoriesRequest create the request corresponding to the list action endpoint of the repositories resource.
func (c *Client) NewListRepositoriesRequest(ctx context.Context, path string, payload *ListPayload, contentType string) (*http.Request, error) {
	var body bytes.Buffer
	if contentType == "" {
		contentType = "*/*" // Use default encoder
	}
	err := c.Encoder.Encode(payload, &body, contentType)
	if err != nil {
		return nil, fmt.Errorf("failed to encode body: %s", err)
	}
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), &body)
	if err != nil {
		return nil, err
	}
	header := req.Header
	if contentType == "*/*" {
		header.Set("Content-Type", "application/json")
	} else {
		header.Set("Content-Type", contentType)
	}
	return req, nil
}

// ShowRepositoriesPath computes a request path to the show action of repositories.
func ShowRepositoriesPath(repoID int) string {
	param0 := strconv.Itoa(repoID)

	return fmt.Sprintf("/v1/repositories/%s", param0)
}

// Retrieve repository from db
func (c *Client) ShowRepositories(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewShowRepositoriesRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewShowRepositoriesRequest create the request corresponding to the show action endpoint of the repositories resource.
func (c *Client) NewShowRepositoriesRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}
